{"name": "Авторизаиця с недействительными учетными данными", "status": "passed", "steps": [{"name": "Открыть страницу авторизации", "status": "passed", "start": 1730275528493, "stop": 1730275529783}, {"name": "Ввести в форму авторизации недействительные учетные данные", "status": "passed", "start": 1730275529783, "stop": 1730275529856}, {"name": "Url не изменился", "status": "passed", "start": 1730275529856, "stop": 1730275529856}, {"name": "Отображается ошибка - Invalid credentials. Please try again.", "status": "passed", "start": 1730275529856, "stop": 1730275529862}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1730275528493, "stop": 1730275529863, "uuid": "a98f25c8-ad21-4559-b461-6ba6d72a691f", "historyId": "3230c37a4ddf37e226b736e144aaba65", "testCaseId": "89a909a1ca222b871b75e39c89c26fa1", "fullName": "tests.test_login#test_login_failure", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "Авторизаци"}, {"name": "story", "value": "Авторизации недействительные учетные данные"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-S2SEQ0A"}, {"name": "thread", "value": "20980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}